# Generated by Django 4.1.5 on 2023-03-15 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapweb', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
